[build]
  publish = "public"
  command = "hugo"

[build.environment]
  HUGO_VERSION = "NA"
  HUGO_BUILDFUTURE = "0.104.3"

[context.deploy-preview.environment]
  command = "hugo --baseURL $DEPLOY_PRIME_URL"

